/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class summm_Main */

#ifndef _Included_summm_Main
#define _Included_summm_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     summm_Main
 * Method:    c_method
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_summm_Main_c_1method
  (JNIEnv *, jobject){
  printf("Hello World!\n");
  };

#ifdef __cplusplus
}
#endif
#endif
